POST http://localhost:8080/rest/signUp
Content-Type: application/json

{
  "email": "marmeladkamarat@gmail.com",
  "username": "111",
  "password": "111"
}

###

POST http://localhost:8080/rest/signIn
Content-Type: application/json

{
  "email": "marmeladkamarat@gmail.com",
  "password": "111"
}

###

GET http://localhost:8080/rest/profile
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiZW1haWwiOiJtYXJtZWxhZGthbWFyYXRAZ21haWwuY29tIiwidXNlcm5hbWUiOiIxMTEifQ.CJRcAwFqk0aCfnXL0VtuvoyU3iUP-vSeNvKTjeOAMZ4
###